# Generated by Django 2.2.10 on 2020-05-05 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200504_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('content', models.CharField(max_length=4000)),
                ('content_short', models.CharField(max_length=2000)),
                ('source_uri', models.URLField(blank=True)),
                ('image_uri', models.URLField(blank=True)),
                ('display_time', models.DateField()),
                ('importance', models.SmallIntegerField()),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('updated_date', models.DateField(auto_now=True, null=True)),
            ],
        ),
    ]
