# Generated by Django 2.2.10 on 2020-05-18 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200505_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_index=True, max_length=256)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(db_index=True, max_length=256),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=256)),
                ('short_name', models.CharField(blank=True, db_index=True, max_length=256)),
                ('uri_name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=4000)),
                ('world_rank', models.IntegerField()),
                ('region_rank', models.IntegerField()),
                ('total_earnings', models.DecimalField(decimal_places=10, max_digits=19)),
                ('win_rate', models.DecimalField(decimal_places=10, max_digits=19)),
                ('starting_date', models.DateTimeField()),
                ('banner_in_list_uri', models.URLField(blank=True)),
                ('banner_in_detail_uri', models.URLField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Status')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_index=True, max_length=256)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Status')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('short_name', models.CharField(blank=True, db_index=True, max_length=256)),
                ('uri_name', models.CharField(max_length=256)),
                ('starting_date', models.DateTimeField()),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Status')),
                ('team_left', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_match_team_left', to='api.Team')),
                ('team_right', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_match_team_right', to='api.Team')),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('league_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=256)),
                ('uri_name', models.CharField(db_index=True, max_length=256)),
                ('description', models.CharField(max_length=4000)),
                ('price_pool', models.DecimalField(decimal_places=10, max_digits=19)),
                ('starting_date', models.DateTimeField()),
                ('banner_in_list_uri', models.URLField(blank=True)),
                ('banner_in_detail_uri', models.URLField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Status')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=256)),
                ('uri_name', models.CharField(db_index=True, max_length=256)),
                ('description', models.CharField(max_length=4000)),
                ('icon_uri', models.URLField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Status')),
            ],
        ),
    ]
