# Generated by Django 2.2.10 on 2020-05-18 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200518_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='short_name',
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Status'),
        ),
        migrations.AddField(
            model_name='team',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Region'),
        ),
        migrations.AlterField(
            model_name='match',
            name='uri_name',
            field=models.CharField(db_index=True, max_length=256),
        ),
    ]
