# Generated by Django 2.2.10 on 2020-05-23 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200523_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='league_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='league_game', to='api.Game'),
        ),
    ]
