# Generated by Django 2.2.10 on 2020-05-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200524_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
    ]
