# Generated by Django 2.1 on 2020-04-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='createDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
